### PR TITLE
Eslint rules and precommit linting

### LINKED ISSUE #10: Improve ESLint / standardized code formatting
Although ESLint has been set up, it doesn't run on every commit, and the settings haven't been audited to ensure that code comes out consistently with each pass (a la Prettier, and it's possible a Prettier + ESLint configuration is necessary to achieve this, but would be less desirable than a ESLint-only configuration).

This issue could be broken up into 2 issues if necessary:

- running some form of linting/formatting on a pre-commit hook, such as with Husky or by directly writing a hook
- configuring ESLint and/or Prettier to consistently format code on the lint run-script

### PR DESCRIPTION
**Pull request by codysherman**
Resolves #10 

This PR improves upon the eslint rules past `eslint:recommended` and runs `npm run lint` (which now includes `--fix`) pre-commit via Husky.

It also does add a .vscode folder to recommend VS Code users the Eslint extension, and forces some basic project settings.

I resolved all eslint errors except for two, which have been temporarily blocked from Eslint via:
`// eslint-disable-next-line @typescript-eslint/ban-ts-comment`

Both errors are inside of `rtcpeer/src/util/typed-event-target.ts`

Non-autofixable warnings also remain, but do not block commits.

Finally, a lot of comments in the code break the 100 max-length character rule, so I've disabled the rule on comments only. You can choose to keep that or fix the comments.

### CODE REVIEW

File: src/util/typed-event-target.ts [hunk 1]
```diff
@@ -32,13 +32,14 @@ export class TypedEventTarget<T extends AnyEventMap, EventMap = SomeEventMap<T>>
   >(
     type: K | string,
     listener: (ev: E) => void | EventListenerOrEventListenerObject | null,
-    options?: boolean | AddEventListenerOptions
+    options?: boolean | AddEventListenerOptions,
   ): void {
     super.addEventListener(
       type,
+      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
```
Comment (sammoore) [inline src/util/typed-event-target.ts:39]: 👍

File: .eslintrc.js [hunk 2]
```diff
@@ -0,0 +1,44 @@
+module.exports = {
```
Comment (sammoore) [inline .eslintrc.js:1]: Switching to JS from JSON seems unnecessary but I'll allow it... does this provide linting support/fixes within the config itself since it's not JSON?

File: .eslintignore [hunk 3]
```diff
@@ -12,3 +12,5 @@ src/**/*.js
 src/**/*.map
 src/**/*.d.ts
 
+# Include eslint config
+!.eslintrc.js
```
Comment (sammoore) [inline .eslintignore:16]: The above `*.js` rule (which makes this `!.eslintrc.js` necessary) is probably no longer needed -- `src/index.js` used to be at the root of the repository, which is why the `*.js` rule is still around.

I think we can just remove the above `*.js`, `*.map`, and `*.d.ts` rules and remove this line as well. The same applies to the `.gitignore` file as well.

**Review by sammoore — CHANGES_REQUESTED** [review]
Just one change on the eslintignore/gitignore -- there are some old rules around that made the `.eslintrc.js` line necessary.

File: .eslintignore (hunk 3 above)
Comment (sammoore) [reply .eslintignore:16]: This actually requires more fixing outside of the scope of this PR.

The underlying gitignore rules that I said could be removed are actually breaking the `examples/cameras/` project, and will be fixed in #19, so I'm not going to block this PR on this issue/fix.

**Review by sammoore — APPROVED** [review]
